// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReceiptCapture.Data;

#nullable disable

namespace ReceiptCapture.Data.Migrations
{
    [DbContext(typeof(ReceiptContext))]
    [Migration("20260326095218_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReceiptCapture.Data.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("ColorCode")
                        .HasColumnType("text");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ColorCode = "#FF6B6B",
                            Description = "Restaurants, cafes, groceries",
                            Icon = "fa-utensils",
                            IsDefault = true,
                            Name = "Food & Dining"
                        },
                        new
                        {
                            CategoryId = 2,
                            ColorCode = "#4ECDC4",
                            Description = "Fuel, parking, public transport",
                            Icon = "fa-car",
                            IsDefault = true,
                            Name = "Transportation"
                        },
                        new
                        {
                            CategoryId = 3,
                            ColorCode = "#45B7D1",
                            Description = "Clothing, electronics, general shopping",
                            Icon = "fa-shopping-bag",
                            IsDefault = true,
                            Name = "Shopping"
                        },
                        new
                        {
                            CategoryId = 4,
                            ColorCode = "#96CEB4",
                            Description = "Movies, games, subscriptions",
                            Icon = "fa-film",
                            IsDefault = true,
                            Name = "Entertainment"
                        },
                        new
                        {
                            CategoryId = 5,
                            ColorCode = "#FFEAA7",
                            Description = "Electric, water, internet, phone",
                            Icon = "fa-bolt",
                            IsDefault = true,
                            Name = "Utilities"
                        },
                        new
                        {
                            CategoryId = 6,
                            ColorCode = "#DDA0DD",
                            Description = "Medical, pharmacy, insurance",
                            Icon = "fa-medkit",
                            IsDefault = true,
                            Name = "Healthcare"
                        },
                        new
                        {
                            CategoryId = 7,
                            ColorCode = "#98D8C8",
                            Description = "Courses, books, training",
                            Icon = "fa-graduation-cap",
                            IsDefault = true,
                            Name = "Education"
                        },
                        new
                        {
                            CategoryId = 8,
                            ColorCode = "#B0B0B0",
                            Description = "Miscellaneous expenses",
                            Icon = "fa-tag",
                            IsDefault = true,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("ReceiptCapture.Data.Models.Receipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReceiptId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("MYR");

                    b.Property<string>("ImageFileId")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("MerchantName")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawText")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReceiptDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("ReceiptTime")
                        .HasColumnType("interval");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ReceiptId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ReceiptDate");

                    b.HasIndex("UserId", "UploadedAt");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("ReceiptCapture.Data.Models.ReceiptItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<string>("ItemName")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("ItemId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptItems");
                });

            modelBuilder.Entity("ReceiptCapture.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ReceiptCapture.Data.Models.Category", b =>
                {
                    b.HasOne("ReceiptCapture.Data.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("ReceiptCapture.Data.Models.Receipt", b =>
                {
                    b.HasOne("ReceiptCapture.Data.Models.Category", "Category")
                        .WithMany("Receipts")
                        .HasForeignKey("CategoryId");

                    b.HasOne("ReceiptCapture.Data.Models.User", "User")
                        .WithMany("Receipts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReceiptCapture.Data.Models.ReceiptItem", b =>
                {
                    b.HasOne("ReceiptCapture.Data.Models.Receipt", "Receipt")
                        .WithMany("Items")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("ReceiptCapture.Data.Models.Category", b =>
                {
                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("ReceiptCapture.Data.Models.Receipt", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ReceiptCapture.Data.Models.User", b =>
                {
                    b.Navigation("Receipts");
                });
#pragma warning restore 612, 618
        }
    }
}
